export const SLIDE_INFO = [
    { title: '서비스 소개', 
      subTitle: 'ㅇㅇㅇ은 코로나 이후 배달 음식 섭취 증가로 인한 저하된 체력과 면역력을 증진시키기 위한 집 주변 산책로 추천 서비스입니다.',
      contents: '' },
    { title: '코로나로 인한 배달 증가', 
      subTitle: '몇퍼 늘고 몇퍼 줌',
      contents: '' },
    { title: '배달 음식 섭취로 인한 건강 악화', 
      subTitle: '국민들의 건강이~',
      contents: '' },
    { title: '산책로 지도', 
      subTitle: '서울시 산책로 지도를 이용',
      contents: '' },
    { title: '팀원 소개', 
      subTitle: '함께 고생한 팀원들',
      contents: '' },
];
